version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.express-sequelize
      secrets:
        - github_token
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fvshop
      POSTGRES_USER: ${DB_USERNAME}
    env_file:
      - .env
    volumes:
      - ./database/entrypoint.sh:/docker-entrypoint-initdb.d/10_postgis.sh
    networks:
      - app_network
    ports:
      - "5432:5432"
networks:
  app_network:
    driver: bridge

secrets:
  github_token:
    file: $HOME/.git/token